# Generated by Django 3.1.5 on 2021-01-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='Display type')),
                ('resolution', models.CharField(max_length=255, verbose_name='Display resolution')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='Accumulater volume')),
                ('ram', models.CharField(max_length=255, verbose_name='Ram ')),
                ('sd', models.BooleanField(default=False)),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Main camera MP')),
                ('front_cam_mp', models.CharField(max_length=255, verbose_name='Front camera MP')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaptopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Diagonal')),
                ('display', models.CharField(max_length=255, verbose_name='Display type')),
                ('cpu_freq', models.CharField(max_length=255, verbose_name='Cpu freq')),
                ('ram', models.CharField(max_length=255, verbose_name='Ram ')),
                ('video', models.CharField(max_length=255, verbose_name='Videocard')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Time without charge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
