# Generated by Django 3.1.5 on 2021-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_laptopproduct_phoneproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopproduct',
            name='cpu',
            field=models.CharField(default='i', max_length=255, verbose_name='Processor Family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopproduct',
            name='cpu_name',
            field=models.CharField(default='i', max_length=255, verbose_name='Processor Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptopproduct',
            name='storage',
            field=models.CharField(default='i', max_length=255, verbose_name='Storage Capacity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptopproduct',
            name='diagonal',
            field=models.CharField(max_length=255, verbose_name='Screen size'),
        ),
        migrations.AlterField(
            model_name='laptopproduct',
            name='display',
            field=models.CharField(max_length=255, verbose_name='Screen resolution'),
        ),
        migrations.AlterField(
            model_name='laptopproduct',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Ram'),
        ),
    ]
