# Generated by Django 2.2 on 2021-02-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20210124_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaptopProduct',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='PhoneProduct',
            new_name='Phone',
        ),
    ]
